// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './shots/ai-1/Ai1Door';
import Shot1, { compositionConfig as cfg1 } from './shots/short-1/Short1Chess';
import Shot2, { compositionConfig as cfg2 } from './shots/short-10/Short10Fees';
import Shot3, { compositionConfig as cfg3 } from './shots/short-11/Short11Map';
import Shot4, { compositionConfig as cfg4 } from './shots/short-12/Short12Orbit';
import Shot5, { compositionConfig as cfg5 } from './shots/short-2/Short2Math';
import Shot6, { compositionConfig as cfg6 } from './shots/short-3/Short3Algo';
import Shot7, { compositionConfig as cfg7 } from './shots/short-4/Short4Reflog';
import Shot8, { compositionConfig as cfg8 } from './shots/short-5/Short5Monty';
import Shot9, { compositionConfig as cfg9 } from './shots/short-6/Short6Sheet';
import Shot10, { compositionConfig as cfg10 } from './shots/short-7/Short7Kids';
import Shot11, { compositionConfig as cfg11 } from './shots/short-8/Short8Phish';
import Shot12, { compositionConfig as cfg12 } from './shots/short-9/Short9Chords';
import Shot13, { compositionConfig as cfg13 } from './shots/vox-1/Vox1Coffee';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
  { Comp: Shot5 as React.FC, config: cfg5 },
  { Comp: Shot6 as React.FC, config: cfg6 },
  { Comp: Shot7 as React.FC, config: cfg7 },
  { Comp: Shot8 as React.FC, config: cfg8 },
  { Comp: Shot9 as React.FC, config: cfg9 },
  { Comp: Shot10 as React.FC, config: cfg10 },
  { Comp: Shot11 as React.FC, config: cfg11 },
  { Comp: Shot12 as React.FC, config: cfg12 },
  { Comp: Shot13 as React.FC, config: cfg13 },
];
